language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ultraspicy/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ultraspicy/docker-react npm run test
